#
###################################
# Site wide configuration
####################################
#
title:
  en: "Rodrigo Bresan - Mobile Development"
  pt: "Rodrigo Bresan - Software e Desenvolvimento Móvel"
  es: "Rodrigo Bresan - Mobile Desenvolvimento"
description:
  en: "Mobile Development"
  pt: "Software e Desenvolvimento Móvel"
  es: "Mobile Desenvolvimento"

read_also:
  en: "Read also in "
  pt: "Leia também em "
  es: "Leer también en "

url:         # the base hostname & protocol for your site

index:
  en:
  pt: pt-br/
  es: es/

archive:
  en: "archive.html"
  pt: "/pt-br/arquivo.html"
  es: "/es/arquivo.html"

categories:
  en: "categories.html"
  pt: "/pt-br/categorias.html"
  es: "/es/categorias.html"

tags:
  en: "tags.html"
  pt: "/pt-br/tags.html"
  es: "/es/tags.html"

sidebar_languages:
  en:
    name: "en"
    url: "/index.html"
  pt:
    name: "pt-br"
    url: "/pt-br/index.html"
  es:
    name: "es"
    url: "/es/index.html"

sidebar_owner:
  en:
    home:
      name: "Home"
      url: "/index.html"
    about:
      name: "About"
      url: "/about.html"
  pt:
    home:
      name: "Início"
      url: "/pt-br"
    about:
      name: "Sobre"
      url: "/pt-br/sobre.html"
  es:
    home:
      name: "Inicio"
      url: "/es"
    about:
      name: "Acerca"
      url: "/es/acerca.html"

sidebar_pages:
  en:
    archive:
      name: "Archive"
      url: "/archive.html"
    categories:
      name: "Categories"
      url: "/categories.html"
    tags:
      name: "Tags"
      url: "/tags.html"
  pt:
    archive:
      name: "Arquivo"
      url: "/pt-br/arquivo.html"
    categories:
      name: "Categorias"
      url: "/pt-br/categorias.html"
    tags:
      name: "Tags"
      url: "/pt-br/tags.html"
  es:
    archive:
      name: "Arquívo"
      url: "/es/arquivo.html"
    categories:
      name: "Categorías"
      url: "/es/categorias.html"
    tags:
      name: "Marcaciones"
      url: "/es/tags.html"

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

gems: [jekyll-paginate]
paginate:         5
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Rodrigo Bresan
  avatar: avatar.jpeg
  job:
    en: "Mobile Developer"
    pt: "Desenvolvedor Móvel"
    es: "Cucaracha"
  bio:
    en: "Mobile Developer"
    pt: "Desenvolvedor Movel"
    es: "Arriba"
  email:
  disqus-shortname: bresan
  twitter:
  facebook: rodrigobresan
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rcbresan
  stackoverflow: 6432460/rodrigo-bresan
  linkedin: bresan
  xing: bresan
  instagram: bresan
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
